"""empty message

Revision ID: 383b62b73e97
Revises: 7758bbc33ab3
Create Date: 2024-08-25 21:38:14.106419

"""

# this file is Alembic migration script that handles schema changes in a SQL database. 
# Alembic is a migration tool used with SQLAlchemy to manage database schema versions.
# Database Management: This migration script ensures that the database schema stays in sync with the application code.
# It helps handle schema changes in the database over time.	

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '383b62b73e97'
down_revision = '7758bbc33ab3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('course_duration_years',
               existing_type=mysql.DECIMAL(precision=3, scale=1),
               type_=sa.Numeric(precision=5, scale=1),
               existing_nullable=True)

    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_column('estimated_cost')
        batch_op.drop_column('pr_probability')
        batch_op.drop_column('estimated_duration_years')
        batch_op.drop_column('recommendation_rank')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recommendation_rank', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('estimated_duration_years', mysql.DECIMAL(precision=3, scale=1), nullable=True))
        batch_op.add_column(sa.Column('pr_probability', mysql.DECIMAL(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('estimated_cost', mysql.DECIMAL(precision=10, scale=2), nullable=True))

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('course_duration_years',
               existing_type=sa.Numeric(precision=5, scale=1),
               type_=mysql.DECIMAL(precision=3, scale=1),
               existing_nullable=True)

    # ### end Alembic commands ###
