"""empty message

Revision ID: 7758bbc33ab3
Revises: d849b3157e26
Create Date: 2024-08-25 19:15:32.200955

"""
# This script handles schema changes in the 'recommendations' table by removing and restoring a foreign key constraint 
# and the associated column.


from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7758bbc33ab3'
down_revision = 'd849b3157e26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_constraint('recommendations_ibfk_2', type_='foreignkey')
        batch_op.drop_column('occupation_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('occupation_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('recommendations_ibfk_2', 'skilled_occupation_list', ['occupation_id'], ['occupation_id'])

    # ### end Alembic commands ###
